# Advent of Code Challenges - Day 12

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

from pandas import Series,DataFrame

## Load Data

In [6]:
input_path = './input.txt'

with open(input_path) as f:
    lines = f.readlines()
f.close()

# transform data
df = DataFrame([line.replace("\n","").split("-") for line in lines], columns = ['A', 'B'])
df

      A      B
0    kc     qy
1    qy     FN
2    kc     ZP
3   end     FN
4    li     ZP
5    yc  start
6   end     qy
7    yc     ZP
8    wx     ZP
9    qy     li
10   yc     li
11   yc     wx
12   kc     FN
13   FN     li
14   li     wx
15   kc     wx
16   ZP  start
17   li     kc
18   qy     nv
19   ZP     qy
20   nv     xr
21   wx  start
22  end     nv
23   kc     nv
24   nv     XQ

## Define Functions

## Puzzle 1 - The quickest way through, is every way through!
Find every possible path from 'start' to 'end' by traversing the cave structure from one cave point 'A' to another 'B' (or 'B' to 'A')

Rules:
1. You can only travel to a 'small cave' (denoted by lower case lettering) once in a path

In [21]:
cave_dict = {}
for a, b in df.values:
    if a not in cave_dict.keys():
        cave_dict[a] = []
    if b not in cave_dict.keys():
        cave_dict[b] = []
    cave_dict[a].append(b)
    cave_dict[b].append(a)

# find terminal small caves attached to other small caves, remove them.
drop_list = []
for key in cave_dict.keys():
    if key.lower() == key and len(cave_dict[key]) == 1:
        drop_list.append(key)
for item in drop_list:
    del cave_dict[item]
    for key in cave_dict.keys():
        if item in cave_dict[key]:
            cave_dict[key].remove(item)

# determine in and out options for each cave
for key in cave_dict.keys():
    if key == 'start':
        cave_in_list = []
        cave_out_list = cave_dict[key]
        for sub_key in cave_dict.keys():
            if 'start' in cave_dict[sub_key]:
                cave_dict[sub_key].remove('start')
    elif key == 'end':
        cave_in_list = cave_dict[key]
        cave_out_list = []
    else:
        pass

SyntaxError: invalid syntax (<ipython-input-21-6a7be6d9e671>, line 22)

## Puzzle 2